// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcmolehaquqldfxqtqst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbW9sZWhhcXVxbGRmeHF0cXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMjgzNDksImV4cCI6MjA3MzgwNDM0OX0.9WU3YXSwtuX6nl1KnJp74UBXOfEIo6gF2Na0UCJ3kNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});